// <auto-generated />
using CurvaStore.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurvaStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240713033528_AddCategoryRows")]
    partial class AddCategoryRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurvaStore.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Football Wear"
                        },
                        new
                        {
                            id = 2,
                            Name = "Football"
                        },
                        new
                        {
                            id = 3,
                            Name = "Sports Bags"
                        },
                        new
                        {
                            id = 4,
                            Name = "Clothing"
                        },
                        new
                        {
                            id = 5,
                            Name = "Accessories"
                        },
                        new
                        {
                            id = 6,
                            Name = "Sports Shoes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
